### PR TITLE
feat: update Next.js multi-language tutorial

### PR DESCRIPTION
**Pull request by lisilinhart**

### CODE REVIEW

**Comment by dawa-liverpudlian** [comment]
Does this changes work ?

**Comment by lisilinhart** [comment]
I am in the process of rewriting the whole tutorial, should be live today or tomorrow

**Comment by dawa-liverpudlian** [comment]
> I am in the process of rewriting the whole tutorial, should be live today or tomorrow

Will preview url other than localhost work with the new code you have written or did it work with the getInitialProps as well? I couldn't make my custom preview url to work with getInitialProps.

**Comment by dawa-liverpudlian** [comment]
> I am in the process of rewriting the whole tutorial, should be live today or tomorrow

It would be great if you could give some tips on how to migrate from the previous tutorial to the new one because there might be people like me who have already started the project with the previous set up that is using getInitialProps. Hoping to see the new tutorial ASAP.

**Comment by lisilinhart** [comment]
Hey Dawa, the tutorial will provide a link to copy the whole setup to use. If you write me on our Discord, it will be easier to help.

**Pull request merged**
